AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for hosting infrastructure'

Parameters:
  Environment:
    Type: String
    Default: "dev"
    AllowedValues: 
      - "dev"
      - "staging"
      - "prod"
    Description: The environment this template is being deployed to
    
  DomainName:
    Type: String
    Description: Domain name for the application (e.g., example.com)

  UserPoolId:
    Type: String
    Description: ID of the Cognito User Pool
    
  UserPoolClientId:
    Type: String
    Description: ID of the Cognito User Pool Client

Resources:
  # Certificate for CloudFront (must be in us-east-1)
  CloudFrontCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "app.${DomainName}"
      SubjectAlternativeNames:
        - !Sub "*.${DomainName}"
      ValidationMethod: DNS
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-cloudfront-cert"
        - Key: Environment
          Value: !Ref Environment

  # Certificate for ALB (in the current region)
  AlbCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "api.${DomainName}"
      ValidationMethod: DNS
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-alb-cert"
        - Key: Environment
          Value: !Ref Environment

  # VPC and Networking resources
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub 'cognito-auth-demo-${Environment}-vpc'
        - Key: Environment
          Value: !Ref Environment

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub 'cognito-auth-demo-${Environment}-igw'
        - Key: Environment
          Value: !Ref Environment

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # Public subnet in AZ1
  PublicSubnetAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select 
        - 0
        - !GetAZs 
          Ref: 'AWS::Region'
      Tags:
        - Key: Name
          Value: !Sub 'cognito-auth-demo-${Environment}-public-subnet-az1'
        - Key: Type
          Value: Public
        - Key: Environment
          Value: !Ref Environment

  # Public subnet in AZ2
  PublicSubnetAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select 
        - 1
        - !GetAZs 
          Ref: 'AWS::Region'
      Tags:
        - Key: Name
          Value: !Sub 'cognito-auth-demo-${Environment}-public-subnet-az2'
        - Key: Type
          Value: Public
        - Key: Environment
          Value: !Ref Environment

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub 'cognito-auth-demo-${Environment}-public-route-table'
        - Key: Environment
          Value: !Ref Environment

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetAZ1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetAZ1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnetAZ2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetAZ2
      RouteTableId: !Ref PublicRouteTable

  # S3 and CloudFront for the React app
  ReactAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'cognito-auth-demo-${Environment}-${AWS::AccountId}'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref Environment

  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "OAI for ${AWS::StackName}"

  ReactAppBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ReactAppBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Sub '${ReactAppBucket.Arn}/*'
            Principal:
              CanonicalUser: !GetAtt CloudFrontOAI.S3CanonicalUserId

  ReactAppCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt ReactAppBucket.RegionalDomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        ViewerCertificate:
          AcmCertificateArn: !Ref CloudFrontCertificate
          SslSupportMethod: 'sni-only'
          MinimumProtocolVersion: 'TLSv1.2_2021'
        Aliases: 
          - !Sub "app.${DomainName}"
        PriceClass: PriceClass_100
        HttpVersion: http2
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-cloudfront"
        - Key: Environment
          Value: !Ref Environment

  # Next.js API hosting
  NextJsApiSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for NextJs API instance
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Environment
          Value: !Ref Environment

  NextJsApiInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMI]
      IamInstanceProfile: !ImportValue 
        !Sub 'CognitoAuthDemo-${Environment}-ApplicationInstanceProfileName'
      SecurityGroupIds:
        - !Ref NextJsApiSecurityGroup
      SubnetId: !Ref PublicSubnetAZ1
      Tags:
        - Key: Name
          Value: !Sub 'cognito-auth-demo-${Environment}-nextjs'
        - Key: Environment
          Value: !Ref Environment
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum update -y
          yum install -y nodejs npm git
          amazon-linux-extras install -y nginx1
          
          # Set up Nginx with SSL
          cat > /etc/nginx/conf.d/nextjs.conf << 'EOL'
          server {
              listen 80;
              server_name _;
              
              # Redirect HTTP to HTTPS
              location / {
                  return 301 https://$host$request_uri;
              }
          }
          
          server {
              listen 443 ssl;
              server_name _;
              
              ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
              ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;
              
              location / {
                  proxy_pass http://localhost:3000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_cache_bypass $http_upgrade;
              }
          }
          EOL
          
          mkdir -p /etc/ssl/private
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
            -keyout /etc/ssl/private/nginx-selfsigned.key \
            -out /etc/ssl/certs/nginx-selfsigned.crt \
            -subj "/C=US/ST=State/L=City/O=Organization/CN=localhost"
          
          systemctl enable nginx
          systemctl start nginx

  NextJsLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Scheme: internet-facing
      SecurityGroups:
        - !Ref NextJsApiSecurityGroup
      Subnets:
        - !Ref PublicSubnetAZ1
        - !Ref PublicSubnetAZ2
      Tags:
        - Key: Name
          Value: !Sub 'cognito-auth-demo-${Environment}-alb'
        - Key: Environment
          Value: !Ref Environment

  NextJsTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckPath: /api/health
      HealthCheckProtocol: HTTPS
      Port: 443
      Protocol: HTTPS
      TargetType: instance
      VpcId: !Ref VPC
      Targets:
        - Id: !Ref NextJsApiInstance
      Tags:
        - Key: Environment
          Value: !Ref Environment

  HttpsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref NextJsTargetGroup
      LoadBalancerArn: !Ref NextJsLoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref AlbCertificate
      SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06

  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: '443'
            Host: '#{host}'
            Path: '/#{path}'
            Query: '#{query}'
            StatusCode: HTTP_301
      LoadBalancerArn: !Ref NextJsLoadBalancer
      Port: 80
      Protocol: HTTP

  # Route 53 for DNS
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName
      HostedZoneConfig:
        Comment: !Sub "Hosted zone for ${AWS::StackName}"
      
  CloudFrontDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Sub "app.${DomainName}."
      Type: A
      AliasTarget:
        DNSName: !GetAtt ReactAppCloudFront.DomainName
        HostedZoneId: Z2FDTNDATAQYW2  # CloudFront hosted zone ID
        EvaluateTargetHealth: false
        
  ApiDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Sub "api.${DomainName}."
      Type: A
      AliasTarget:
        DNSName: !GetAtt NextJsLoadBalancer.DNSName
        HostedZoneId: !GetAtt NextJsLoadBalancer.CanonicalHostedZoneID
        EvaluateTargetHealth: true

  # Additional parameters specific to hosted environment
  ReactAppUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/CognitoAuthDemo/${Environment}/REACT_APP_URL'
      Type: String
      Value: !Sub 'https://app.${DomainName}'
      Description: URL of the React application
      Tier: Standard
      Tags:
        Environment: !Ref Environment
        
  NextJsApiUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/CognitoAuthDemo/${Environment}/NEXTJS_API_URL'
      Type: String
      Value: !Sub 'https://api.${DomainName}'
      Description: URL of the Next.js API
      Tier: Standard
      Tags:
        Environment: !Ref Environment

  CorsAllowedOriginsParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/CognitoAuthDemo/${Environment}/CORS_ALLOWED_ORIGINS'
      Type: String
      Value: !Sub 'https://app.${DomainName}'
      Description: Allowed origins for CORS
      Tier: Standard
      Tags:
        Environment: !Ref Environment

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0c02fb55956c7d316  # Amazon Linux 2023 AMI for us-east-1
    us-east-2:
      AMI: ami-07bc04fdc13241142  # Amazon Linux 2023 AMI for us-east-2
    us-west-1:
      AMI: ami-07bc04fdc13241142  # Amazon Linux 2023 AMI for us-west-1
    us-west-2:
      AMI: ami-07bc04fdc13241142  # Amazon Linux 2023 AMI for us-west-2
    eu-west-1:
      AMI: ami-07bc04fdc13241142  # Amazon Linux 2023 AMI for eu-west-1
    eu-central-1:
      AMI: ami-07bc04fdc13241142  # Amazon Linux 2023 AMI for eu-central-1

Outputs:
  ReactAppUrl:
    Description: URL of the React application
    Value: !Sub 'https://app.${DomainName}'

  NextJsApiUrl:
    Description: URL of the Next.js API
    Value: !Sub 'https://api.${DomainName}'

  VpcId:
    Description: ID of the VPC
    Value: !Ref VPC

  PublicSubnetAZ1Id:
    Description: ID of the first public subnet
    Value: !Ref PublicSubnetAZ1

  PublicSubnetAZ2Id:
    Description: ID of the second public subnet
    Value: !Ref PublicSubnetAZ2