AWSTemplateFormatVersion: '2010-09-09'
Description: 'Central Authentication Service - Cognito Infrastructure'

Parameters:
  Environment:
    Type: String
    Default: "dev"
    AllowedValues: 
      - "dev"
      - "staging"
      - "prod"
    Description: The environment this template is being deployed to

  ServiceName:
    Type: String
    Description: Name for the central auth service
    Default: "AuthService"

  CognitoDomainPrefix:
    Type: String
    Description: Prefix for the Cognito domain (e.g., yourbrand-auth)
    Default: "wilderness-auth"
    
  LocalDevUrls:
    Type: CommaDelimitedList
    Description: Comma-separated list of local development URLs
    Default: "http://localhost:3000,http://localhost:3001"
    
  ProdUrls:
    Type: CommaDelimitedList
    Description: Comma-separated list of production URLs (optional for dev)
    Default: ""

Resources:
  # Core Cognito resources
  CognitoStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://login-service-cf.s3.amazonaws.com/cognito.yaml
      Parameters:
        Environment: !Ref Environment
        UserPoolName: !Sub "${ServiceName}-UserPool"
        CognitoDomainPrefix: !Ref CognitoDomainPrefix
        # Combine local and prod callbacks/logout URLs
        CallbackUrls: !Join 
          - ','
          - - !Join ['/callback,', !Ref LocalDevUrls]
            - !If [HasProdUrls, !Join ['/callback,', !Ref ProdUrls], '']
        LogoutUrls: !Join 
          - ','
          - - !Join [',', !Ref LocalDevUrls]
            - !If [HasProdUrls, !Join [',', !Ref ProdUrls], '']

  # IAM permissions for Cognito access
  IamStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: CognitoStack
    Properties:
      TemplateURL: https://login-service-cf.s3.amazonaws.com/iam.yaml
      Parameters:
        Environment: !Ref Environment
        ServiceName: !Ref ServiceName
        UserPoolId: !GetAtt CognitoStack.Outputs.UserPoolId

  # Core parameters needed for applications
  ParamsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: CognitoStack
    Properties:
      TemplateURL: https://login-service-cf.s3.amazonaws.com/params-core.yaml
      Parameters:
        Environment: !Ref Environment
        ServiceName: !Ref ServiceName
        UserPoolId: !GetAtt CognitoStack.Outputs.UserPoolId
        UserPoolClientId: !GetAtt CognitoStack.Outputs.UserPoolClientId
        UserPoolClientSecret: !GetAtt CognitoStack.Outputs.UserPoolClientSecretValue

Conditions:
  HasProdUrls: !Not [!Equals [!Select [0, !Ref ProdUrls], ""]]

Outputs:
  UserPoolId:
    Description: ID of the Cognito User Pool
    Value: !GetAtt CognitoStack.Outputs.UserPoolId

  UserPoolClientId:
    Description: ID of the Cognito User Pool Client
    Value: !GetAtt CognitoStack.Outputs.UserPoolClientId

  UserPoolDomainName:
    Description: Domain name of the Cognito User Pool
    Value: !GetAtt CognitoStack.Outputs.UserPoolDomainName

  ParameterPath:
    Description: Base path for all parameters
    Value: !GetAtt ParamsStack.Outputs.ParameterPath